### ISSUE TITLE
Добавить к команде USE флаг -i --install

### ISSUE THREAD

**Issue by khorevaa** [silverbulleters/ovm#10]
При использовании версии, которая не  установлена, делать автоматическую установку

**Comment by nixel2007** [comment]
Изначально планировалось, что use отсутствующей версии кидает исключение. при этом install автоматического use не делает (что вполне ложится на логику множественного install).

Думаешь, автоустановка по флагу не будет излишней сложностью?

**Comment by nixel2007** [comment]
link #2

**Comment by khorevaa** [comment]
как раз в use можно и сделать автоматический install по флагу. А в инсталл не делать use по умолчанию вынести тоже во флаг (допустим )
Меньше команд  лучше воспроизводиться )
