### ISSUE TITLE
Отделить классы работы в версиями и классы консольного приложения

### ISSUE THREAD

**Issue by khorevaa** [silverbulleters/ovm#11]
Создать папки:
* cmd - для классов и модулей приложения
* core - для классов и модулей для работы с версиями oscript

**Comment by nixel2007** [comment]
хочешь `#Использовать`? или ради SRP и разделения cli от core?

**Comment by khorevaa** [comment]
Ради повторного использования классов и модулей без создания класса команды... и публичных методов в нем кроме необходимых

**Comment by nixel2007** [comment]
а, ну это да, думал об этом.

**Comment by khorevaa** [comment]
Могу сделать ))

**Comment by khorevaa** [comment]
Сделал https://github.com/silverbulleters/ovm/pull/12
