### ISSUE TITLE
dev -> night-build, latest -> stable

### ISSUE THREAD

**Issue by nixel2007** [silverbulleters/ovm#16]
dev и latest должны быть симлинками на соответствующие версии, а не отдельными каталогами как сейчас. Учесть в list

**Comment by nixel2007** [comment]
Думаю, проще будет вообще убрать night-build и latest. Оставить один dev и stable. Это упростит код и избавит от неразберихи версий и симлинков. @Khorevaa твоё мнение?

**Comment by khorevaa** [comment]
Я бы latest оставил.. и туда запихивал ночную сборку.

**Comment by nixel2007** [comment]
Вместо дев?

**Comment by khorevaa** [comment]
@nixel2007 От корректировал сообщение

**Comment by khorevaa** [comment]
Хотя выше описанное актуально, если таким же принципам будут придерживаться при выпуске релизов oscript

**Comment by nixel2007** [comment]
Так у нас нет версии для тестирования

**Comment by nixel2007** [comment]
Ну, главный принцип я понял. Два имени одного и того же стоит убрать.
