### ISSUE TITLE
ovm install latest as <alias>

### ISSUE THREAD

**Issue by nixel2007** [silverbulleters/ovm#19]
Установка указанной версии в каталог, отличный от имени версии (алиаса)

**Comment by khorevaa** [comment]
+

**Comment by khorevaa** [comment]
Как вариант реализации: 
Добавить флаг -n --name в команду Install

Хочу иметь возможность создавать именные версии OSCRIPT
Кейс использования:

    Рабочий сервер - используется версия 19. С определенным набором библиотек
    Установка доп. версии 19. (с именем 19-testing-gitsync) обновление там ряда библиотек для тестировать.
    Запуск через ovm run
    Удаление версии - если больше нет в ней необходимости
    Все стандартные либы и апп работают на 19 без каких любо изменений

**Comment by nixel2007** [comment]
Да, все перечисленное можно реализовать без особых проблем. Сделаю на днях
