### ISSUE TITLE
nix: System.TypeLoadException: Could not load file or assembly 'ScriptEngine.HostedScript

### ISSUE THREAD

**Issue by allustin** [silverbulleters/ovm#26]
> lustin@nb-msk-al-01:~$ mono ovm.exe 
> 
> Unhandled Exception:
> System.TypeLoadException: Could not load file or assembly 'ScriptEngine.HostedScript, Version=1.0.20.134, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:ScriptEngine.HostedScript, Version=1.0.20.134, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>
>   at StandaloneRunner.Program.Main (System.String[] args) [0x00016] in <70f09c2e556d4b0fb9d406fdadefeb45>:0 
> [ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load file or assembly 'ScriptEngine.HostedScript, Version=1.0.20.134, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:ScriptEngine.HostedScript, Version=1.0.20.134, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>
>   at StandaloneRunner.Program.Main (System.String[] args) [0x00016] in <70f09c2e556d4b0fb9d406fdadefeb45>:0 
> 

Последняя альфа-7

судя по всему - сам ovm.exe хочет странного, то есть встроенного hostedScript

**Comment by nixel2007** [comment]
Овм не хочет странного, это движок все никак нормально make не разрулит

**Comment by artbear** [comment]
Из описания релиза альфа-8:
>Для работы ovm под *nix необходимо положить рядом с ovm.exe файл ScriptEngine.HostedScript.dll

т.е. это какая-то зависимость от движка конкретной версии, на котором собран ovm.exe?

**Comment by nixel2007** [comment]
не совсем. движок должен упаковывать ScriptEngine.HostedScript.dll внутрь exe, так же как он это делает для ScriptEngine.dll и прочих Newtonsoft.dll. но по какой-то причине именно ScriptEngine.HostedScript.dll не пакуется. из-за этого его приходится иметь отдельно.

**Comment by nixel2007** [comment]
@allustin сделано [14 дней назад](https://github.com/silverbulleters/ovm/releases/tag/v1.0.0-RC5)
