### ISSUE TITLE
При скачивании альфа-8 в хроме выдается ошибка "Обнаружен вирус", файл не скачивается

### ISSUE THREAD

**Issue by artbear** [silverbulleters/ovm#31]
![image](https://user-images.githubusercontent.com/2920817/35674697-967812ba-0756-11e8-908d-98c23ae0ffd0.png)
это на рабочем компе :(

**Comment by nixel2007** [comment]
https://www.virustotal.com/#/url/effcf810f9101e01e2212ebb87fc35e0e0a82b494b4ee166f916f49f88faa550/detection
/cc @EvilBeaver @allustin

**Comment by nixel2007** [comment]
можешь еще раз попробовать? я только что скачал его с домашнего компа

**Comment by artbear** [comment]
Да, сейчас все в порядке.
очень странно.

**Comment by nixel2007** [comment]
возможно помог прогон на вирус-тотале. а еще я +1 в рейтинге сделал :D
