### ISSUE TITLE
Добавить флаг -n --name в команду Install

### ISSUE THREAD

**Issue by khorevaa** [silverbulleters/ovm#35]
Хочу иметь возможность создавать именные версии OSCRIPT
Кейс использования:

1. Рабочий сервер - используется версия 19. С определенным набором библиотек
2. Установка доп. версии 19. (с именем `19-testing-gitsync`) обновление там ряда библиотек для тестировать.
3. Запуск через `ovm run`
4. Удаление версии - если больше нет в ней необходимости
5. Все стандартные либы и апп работают на 19 без каких любо изменений

**Comment by nixel2007** [comment]
дубль #19
