### ISSUE TITLE
Разобраться, почему в PATH много раз добавляется строка OVM_OSCRIPTBIN 

### ISSUE THREAD

**Issue by nixel2007** [silverbulleters/ovm#36]

**Comment by asosnoviy** [comment]
https://github.com/silverbulleters/ovm/blob/develop/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%90%D0%BA%D1%82%D0%B8%D0%B2%D0%B0%D1%82%D0%BE%D1%80OneScript.os#L154

Там же не ПутьККаталогуBin а %OVM_OSCRIPTBIN%

**Comment by nixel2007** [comment]
По идее он должен разрешать все плейсхолдеры сразу... но так оно работает на уровне процесса, на уровне User и Machine свои правила. спасибо, посмотрю.

**Comment by nixel2007** [comment]
Ты охренительно прав...
