### ISSUE TITLE
менять еще и принудительно каталог билиотеки в nix

### ISSUE THREAD

**Issue by allustin** [silverbulleters/ovm#37]
нужно чтобы в profile добавлялось

```
export OSCRIPTBIN="$HOME/.local/share/ovm/current/bin"
```

чтобы установка библиотек проходила в текущий каталог активного движка 

чтобы финальный профиль был 

```
export PATH="$HOME/.local/share/ovm/current/bin:$PATH"
export OSCRIPTBIN="$HOME/.local/share/ovm/current/bin"
```

тогда будет нормально устанавливаиться библиотеки

**Comment by nixel2007** [comment]
под linux переменная oscriptbin вообще не используется. зачем она тебе?

**Comment by nixel2007** [comment]
Аааа, я понял про что ты. Это кусок работы инсталлятора скриптов opm.

Да, хорошая идея, добавлю.

**Comment by nixel2007** [comment]
![image](https://user-images.githubusercontent.com/1132840/36395578-e5d3a0a4-15ca-11e8-82c8-7d99fcae454a.png)
