### ISSUE TITLE
добавить установку eco с аутентификацией

### ISSUE THREAD

**Issue by allustin** [silverbulleters/ovm#42]
добавить метод установки oscript-enterprise-components с аутентификацией

поведение

* новый метод upgrade `token`
* после чего доступен opm install oscript-eco

**Comment by khorevaa** [comment]
А есть такие компоненты? А описание есть посмотреть?

**Comment by allustin** [comment]
@khorevaa да - по во внутреннем git

**Comment by nixel2007** [comment]
1. это не задача ovm. ovm занимается исключительно поставкой движка и небольшой донастройкой батника для opm. 
2. эта задача решается средствами opm через поднятие и добавление зеркала хаба для opm и настройками прокси для доступа к нему. без доработок со стороны opm.

**Comment by allustin** [comment]
@nixel2007 ты скорее всего прав - это к opm
