### ISSUE TITLE
Добавить команды list

### ISSUE THREAD

**Issue by khorevaa** [silverbulleters/ovm#5]
Вывод списка установленных версий 
- флаг r  (remote) доступных к установке
- флаг q (quiet) вывод только версий
- флаг a (all) вывод всех доступных версий и установленных

**Comment by nixel2007** [comment]
All - имеется ввиду вывод установленных версий?

P.S. Предлагаю за эталон приложения взять nvm. Функциональность ovm в первом приближении должна быть сопоставима

**Comment by artbear** [comment]
@nixel2007 Можешь накидать в ишузах команды nvm, которые будешь портировать,

+ команда и ссылка на описание

можно будет уже детальнее обсудить по каждой из команд

**Comment by nixel2007** [comment]
Сделал -q и -r. С учетом выводимых на данный момент данных, дай пример вывода --all с различными флагами.

**Comment by khorevaa** [comment]
--all выводит все версии включая те, что могут быть установлены (флаг -r)
С их полным описанием ()
-q - только имена версий

`ovm install $(ovm ls -aq)` - должна установить (обновить) все доступные версии
