### ISSUE TITLE
После команды use для версии 1.0.21 не работает opm

### ISSUE THREAD

**Issue by khorevaa** [silverbulleters/ovm#52]
В связи с рефакторингом opm поменялся путь к opm.os 
Стало "src/cmd/opm.os"

Для старых версий так и осталось

**Comment by nixel2007** [comment]
@khorevaa возьмешь себе?

https://github.com/silverbulleters/ovm/blob/a2c16c7637b212b399019ee7184edd659e0c4fea/src/core/%D0%9A%D0%BB%D0%B0%D1%81%D1%81%D1%8B/%D0%A3%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D1%89%D0%B8%D0%BAOneScript.os#L112-L119

или мне глянуть?

**Comment by khorevaa** [comment]
@nixel2007 Мне тут не очень удобно - в отпуске ))
Вообще надо подумать как это сделать через чтение описания пакета и генерации на основании ссылку на приложение! А то сейчас поправим тогда старые версии работать не будут

**Comment by nixel2007** [comment]
Можно добавить проверку на устанавливаемую версию.

**Comment by nixel2007** [comment]
Да, я тоже думал о чем-то таком. Если сделаешь - будет круто!

**Comment by khorevaa** [comment]
Тут сразу придется часть из опм  выпилить в отдельную либу  т.к. если подключить как либу  тогда компиляция в ехе  не будет работать...

**Comment by nixel2007** [comment]
почему же? овм содержит ряд либ и компилируется в exe без ошибок.

**Comment by khorevaa** [comment]
Да компиляция будет а вот работа в ехе нет.. там есть ряд методов которые с ехе  не работаю..... точнее не корректно... я этотнашел когда хотел собрать ехе  для гитсинка...

**Comment by khorevaa** [comment]
Вообще очень хочу статическое описание пакета в json..... yaml...

**Comment by khorevaa** [comment]
@nixel2007 Не дождался ))

**Comment by nixel2007** [comment]
@Khorevaa я закостылил. Посмотри последний коммит)
