### ISSUE TITLE
Не работает команда witch

### ISSUE THREAD

**Issue by khorevaa** [silverbulleters/ovm#56]
ovm i dev
ovm w dev
ОШИБКА - {Модуль ovm.exe:ОписанияОповещений / Ошибка в строке: 59 / {Модуль ovm.exe:ПроцессорКоллекцийСлужебный / Ошибка в строке: 56 / Внешнее исключение (System.ArgumentOutOfRangeException): Индекс за пределами диапазона. Индекс должен быть положительным числом, а его размер не должен превышать размер коллекции.
Имя параметра: index}}

ovm@v1.0.0-RC8
/cc @nixel2007

**Comment by nixel2007** [comment]
Хм... Подтверждаю. Даже на винде:
![image](https://user-images.githubusercontent.com/1132840/54538287-0ee79400-49a5-11e9-9d7f-1c4f5780355a.png)
