### ISSUE TITLE
Добавить работу с переменными окружения для опций и аргументов

### ISSUE THREAD

**Issue by khorevaa** [silverbulleters/ovm#6]
Для возможности использования на  ci

**Comment by nixel2007** [comment]
Чем плох запуск на CI с параметрами командной строки? Чтобы что? Просто запустить ovm и все поставилось/использовалось?

**Comment by khorevaa** [comment]
Чтобы сделать матрицу вариантов на тревисе это там делает через переменыне окружения

**Comment by nixel2007** [comment]
Любопытно, как раз сегодня об этом думал. Если есть дока про это дело под рукой, кинь ссылку, пожалуйста

**Comment by khorevaa** [comment]
Дока для тревиса вот тут https://docs.travis-ci.com/user/environment-variables/

**Comment by artbear** [comment]
А не хотите ли вернуться к единому месту к работе с параметрами ком.строки, окружения, файлов настройки вместо того, чтобы дублировать код по их обработке в куче мест?
я про params говорю.

**Comment by nixel2007** [comment]
params прошлый век.

**Comment by artbear** [comment]
а какой инструмент в новом веке, которые выполняют ВСЮ указанную работу?

**Comment by khorevaa** [comment]
@artbear Я честно крутил твой парамс  но он жестко привязан к cmdline и отвзять его мягко говоря не просто...

**Comment by nixel2007** [comment]
@artbear ovm построен поверх cli. Посмотри ее описание и референс. Мне в прикладном коде вообще не надо заботится о переменных окружения, параметрах, их заполненности и прочем.

**Comment by khorevaa** [comment]
@artbear Если из прамс вырезать привязку к cmdline а работат в чистом виде только с переменными окружения + настройки в файле. Т.е. не касаться аргументом командной строки будет то, что надо для cli...  Или сделать это опционально как то так...

**Comment by khorevaa** [comment]
@artbear Если из прамс вырезать привязку к cmdline а работат в чистом виде только с переменными окружения + настройки в файле. Т.е. не касаться аргументом командной строки будет то, что надо для cli...  Или сделать это опционально как то так...
