### ISSUE TITLE
Убейте это реп за ненадобностью

### ISSUE THREAD

**Issue by asosnoviy** [silverbulleters/ovm#63]
Разработка овм ведётся в оскрипт-лайбориари. Этот протухший реп можно смело грохать.

**Comment by artbear** [comment]
Для истории хочу оставить, чтобы форки, ишузы и т.п. остались.
можно написать, что основная разработка ведется в репо oscript-library

**Comment by kuntashov** [comment]
Предлагаю в начале README указать, что это не основной РЕПО + ссылку на основной + архивировать этот.
Сегодня подумал, что этот репо основной (т.к. он родительский).

**Comment by kuntashov** [comment]
https://github.com/vanessa-opensource/ovm/pull/65
