### ISSUE TITLE
Добавить команду exec

### ISSUE THREAD

**Issue by khorevaa** [silverbulleters/ovm#8]
Предполагаемые опции
-s --codestat - путь к файлу покрытия тестами
--encoding - кодировка
-w --work-dir - рабочая директория
-c --oscript-cfg - путь к файлу конфига oscript
Аргументы
VERSION - Версия или Маска версии
FILE - запускаемый файл или пакет (.ospx)
ARGS - аргументы  к запускаемому файлу

**Comment by nixel2007** [comment]
Зачем переопределять родные аргументы oscript? почему не просто `ovm run 1.0.17 ARGS`, где ARGS - обыкновенные аргументы родного oscript.exe?

**Comment by khorevaa** [comment]
Для run думаю пойдет и так для exec опять таки хочется эти родные аргументы запихнуть в переменные окружения что их не задавать в явном виде на ci

**Comment by nixel2007** [comment]
я чуть дописал команду run, наверное ты не заметил. после версии можно указать еще приложение: oscript, opm, deployka - поиск будет вестись по bin конкретной версии. так как имя версии, имя приложения и аргументы приложения - отдельные аргументы на уровне cli, то их можно будет все обозначить через переменные среды.

P.S. если честно, я курю доку по nvm и никак не могу понять, чем run отличается от exec. Возможно exec - это часть нодовского REPL. у нас REPL нет, поэтому остается только RUN

**Comment by nixel2007** [comment]
Пока мы друг друга не совсем поняли, закрою ишуз.
Моя идея реализована командной RUN, переменные окружения все зададим в рамках #6 

Если будут еще идеи по EXEC со сценариями работы - создавай новый ишуз или открывай этот.

**Comment by khorevaa** [comment]
Ок ))
