### ISSUE TITLE
Добавить команду Delete (синоним d)

### ISSUE THREAD

**Issue by khorevaa** [silverbulleters/ovm#9]
или purge или remove или uninstall
Опции 
-a --all - удаление всех установленных версий
Аргументы 
VERSION - массив масок версий к удалению

**Comment by nixel2007** [comment]
@khorevaa хотел с тобой посоветоваться. у nvm по умолчанию нельзя удалить версию, которая сейчас "используется" - кидается эксепшн.

мне такое поведение кажется логичным. как тебе?

при этом очевидно, что в режиме --all такой проверки быть не должно.

**Comment by khorevaa** [comment]
Думаю у нас должно удалять если версия не залочена (т.е. на ней ничего не запущено)

**Comment by khorevaa** [comment]
Кстати это должно казаться и сменить версию

**Comment by khorevaa** [comment]
Хотя просто сделай флаг force для удаления даже используемой версии

**Comment by nixel2007** [comment]
> (т.е. на ней ничего не запущено)
> Кстати это должно казаться и сменить версию

запуск идет синхронно. так что лочится там нечему.

а вот на --force добавлю, да.

**Comment by khorevaa** [comment]
@nixel2007  Ну тогда и хорошо..
